### ISSUE TITLE
How to add API key?

### ISSUE THREAD

**Issue by mlamlamla** [bigcode-project/jupytercoder#38]
Dear team,
thanks for this extension! I have a clarifying question - how do I add my API key?

![grafik](https://github.com/bigcode-project/jupytercoder/assets/26493630/c60a2e86-1d9b-40c3-9ce4-e9e988f3e7ee)

I have a hugging face account; I signed the license agreement for StarCoder; I added the extension in Chrome. I tried entering https://api-inference.huggingface.co/models/bigcode/starcoderbase/hf_*** in the brower and get:

{"error":"Model bigcode/starcoderbase/hf_*** does not exist"}

as response. I also see no way in the settings to prompt the window showed in the READ.ME .

Thanks for clarifying!

**Comment by Wzixiao** [comment]
@mlamlamla 
This might have been an oversight on our part. The correct name should be "Huggingface Access Token". Thanks for pointing it out; we'll address this in the next update. If you're unsure where to find the Huggingface Access Token, just click on your profile picture on the Huggingface homepage, and you'll find it under settings.
 
 So, the usage of "https://api-inference.huggingface.co/models/bigcode/starcoderbase/hf_" is incorrect. Typically, you don't need the "hf_" part. Of course, if you don't add certain authentication configurations, you might get the same error. You might want to look into the request method of this project for specifics. I should also remind you that due to the server experiencing high traffic lately, they might restart the model, which could lead to the same result error.
